feedback/urls.py
from django.urls import path

from . import views

from django.conf.urls import url

urlpatterns = [
    url(r'display_feedback/(?P<session_id>[0-9]+)', views.display_feedback, name='display_feedback'),
    url(r'overview', views.overview, name='overview'),
    url(r'contributors', views.contributors, name='contributors'),
    url(r'', views.submit_feedback, name='submit_feedback')
]

lets_build_something_for_real/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feedback.urls')),
]

feedback/models.py
from django.db import models


class ConferenceDay(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()

    def __str__(self):
        return self.title

class Session(models.Model):
    title = models.CharField(max_length=100)
    conferenceDay = models.ForeignKey(ConferenceDay, related_name='sessions', blank=False, null=True, default=None, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_title_with_feedback_count(self):
        return self.title + " [" + str(self.feedbacks.all().count()) + " reviews]"

    def get_ordered_feedback_list(self):
        return self.feedbacks.all().order_by('-id')


class Feedback(models.Model):
    RATING_CHOICES = (
        (1, 'Disappointing'),
        (2, 'Mwah'),
        (3, 'Ok'),
        (4, 'Great!'),
        (5, 'Amazing!!'),
    )

    session = models.ForeignKey(Session, related_name='feedbacks', blank=False, null=False, default=None, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.CharField(max_length=1000, default='')

    def __str__(self):
        return self.session.title + " (" + str(self.rating) + ")"

class People(models.Model):
    fullname = models.CharField(max_length=100)
    presenter = models.BooleanField()
    contributor = models.BooleanField()

    def __str__(self):
        return self.fullname

feedback/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from annoying.decorators import render_to
from feedback.models import Session, Feedback, People
from django.contrib import messages
from django.db.models import Avg
import datetime

def index(request):
    return HttpResponse("Hello, world. Let's build something for real! More will come soon!")

@render_to('submit_feedback.html')
def submit_feedback(request):
    if request.POST:
        session = Session.objects.filter(id=request.POST['session']).first()
        if session:
            feedback = Feedback(session=session, rating=request.POST['rating'], comment=request.POST['comment'])
            feedback.save()
            return HttpResponseRedirect("/display_feedback/" + str(session.id))
            # messages.info(request, 'Thank you, your feedback has been saved

    #sessions = Session.objects.filter(conferenceDay__date=datetime.datetime.now())
    sessions = Session.objects.all()
    session_without_feedback_count = sessions.filter(feedbacks__isnull=True).count()
    return {'Sessions': sessions, 'FeedbackCount': Feedback.objects.count(), 'SessionWithoutFeedbackCount': session_without_feedback_count}

@render_to('display_feedback.html')
def display_feedback(request, session_id):
    session = Session.objects.filter(id=session_id).first()
    average = session.feedbacks.aggregate(Avg('rating'))['rating__avg']
    return { 'Session': session, 'FeedbackAverage': average }


@render_to('overview.html')
def overview(request):
    return {'feedbacks': Feedback.objects.all()}

@render_to('contributors.html')
def contributors(request):
    return {'people': People.objects.all()}

feedback/templates/base.html
{% load staticfiles %}

<html>

    <link type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">


    <link type="text/css" href="{% static 'commons.css' %}" rel="stylesheet">



    {% block content %}
    {% endblock %}


    <script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
  crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>


    <script type="text/javascript">
    $(document).ready( function () {
        $('#overview').DataTable(
            {"searching": true,
             "pageLength": 100}
        );
    } );
    </script>

</html>

feedback/templates/contributors.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <header>
            <title>XP Days Top Contributors to this tool</title>
    </header>
    <body>
      <center>
        <div class='header'>
          <a href="https://www.xpday.nl/">XP Days website</a> |
          <a href="{% url 'submit_feedback' %}">Rate a session</a> |
          <a href="{% url 'overview' %}">Overview</a>
          <h1>Top Contributors</h1>
        </div>
        <div class='heroic'>
          {% for person in people %}
            {% if person.contributor %}
              <p>{{ person.fullname }}</p>
            {% endif %}
          {% empty %}
            Sorry, no contributors provided.
          {% endfor %}
        </div>
      </center>
    </body>

{% endblock %}

feedback/templates/display_feedback.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <header>
            <title>XP Days Session Feedback</title>
    </header>
    <body>
        <center>
            <div class='header'>
                <h1>Session Feedback</h1>
            </div>
            <p>Thank you, your feedback has been saved</p>
            <h1><a href="{% url 'submit_feedback' %}">Rate another session!</a> </h1>
            <p> {{ Session.title }} </p>
			<p>The average rating of this session is: {{ FeedbackAverage|floatformat:2 }}</p>
            {% for feedback in Session.get_ordered_feedback_list %}
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title"> {{ feedback.get_rating_display }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ feedback.comment }}</h6>
                  </div>
                </div>
            {% endfor %}
        </center>
    </body>

{% endblock %}

feedback/templates/overview.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <header>
            <title>XP Days Overview of feedback</title>
    </header>
    <body>
        <center>
            <div class='header'>
                <a href="https://www.xpday.nl/">XP Days website</a> | 
                <a href="{% url 'submit_feedback' %}">Rate a session</a> |
                <a href="{% url 'contributors' %}">Contributors</a>
                <h1>Overview</h1>
            </div>
            <div>
                <h1><a href="{% url 'submit_feedback' %}">Rate a session</a> </h1>

                <table class="data_table" id='overview'>
                    <thead>
                        <tr>
                            <th>Conference Day</th>
                            <th>Session</th>
                            <th>Rating</th>
                            <th>Comment</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for f in feedbacks %}
                            <tr>
                                <td>{{f.session.conferenceDay.title}}</td>
                                <td><a href="{% url 'display_feedback' f.session.id %}">{{f.session.title}}</a></td>
                                <td>{{f.rating}}</td>
                                <td>{{f.comment}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </center>
    </body>

{% endblock %}

feedback/templates/submit_feedback.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <header>
        <title>XP Days Session Feedback</title>
    </header>
    <body>
      <center>
        <div class='header'>
          <a href="https://www.xpday.nl/">XP Days website</a> |
          <a href="{% url 'overview' %}">Overview</a> |
          <a href="{% url 'contributors' %}">Contributors</a>
          <h1>What's your feedback on the session?</h1>
        </div>
      </center>
        <div class='wrapper'>
            <div>
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <form>
                    {% csrf_token %}
                    <p>
                        <label>Which session did you attend?</label> </br>
                        <select class='selectValue' name='session' required>
                            <option disabled selected value> -- choose session -- </option>
                            {% for session in Sessions %}
                                <option value='{{ session.id }}'>{{ session.get_title_with_feedback_count }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <label>What did you think about it?</label> </br>
                    <p>
                        <select class='selectValue' name='rating' required>
                            <option disabled selected value> -- rating -- </option>
                            <option value='5'>Amazing!</option>
                            <option value='4'>Great!</option>
                            <option value='3'>Ok</option>
                            <option value='2'>Mwah</option>
                            <option value='1'>Disappointing</option>
                        </select>
                        <textarea name='comment' placeholder="Please provide more details"></textarea>
                    </p>

                    <input type="submit" id='submit' value='Submit' formmethod="post">
                </form>
                <a href="{% url 'overview' %}">Overview of feedback</a>
            </div>

            <div class="statisticsContainer">Feedback has been given {{ FeedbackCount }} times.</div>
            <div class="statisticsContainer">There are {{ SessionWithoutFeedbackCount }} sessions without feedback.</div>
        </div>

    </body>


{% endblock %}